Move Coverage Collection into jar file In some projects, the tests fail with a NoClassDefFoundError for GlobalCoverageMonitor. I believe the reason for this is that it is in a different classloader than the code being covered.